---
exclude: migrations|templates|fixtures|__init__.py
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: /
      - id: end-of-file-fixer
        files: /
      - id: check-ast
        files: /
  - repo: https://github.com/myint/autoflake # removes unused imports
    rev: v2.0.1
    hooks:
      - id: autoflake
        files: /
        args:
          [
            -i,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --expand-star-imports,
            --remove-duplicate-keys,
          ]
  - repo: https://github.com/pycqa/isort # sorts imports
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ --settings-file, black.toml]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: /
        language_version: python3
        args: [--config, black.toml]
        additional_dependencies:
          - "click==8.0.4"
  - repo: https://github.com/radix-ai/auto-smart-commit # prepends jira ticket number to each commit
    rev: v1.0.2
    hooks:
      - id: auto-smart-commit